"""sincronizar_aluno_id

Revision ID: 2a4ce4feb92b
Revises: fb20cc474ff8
Create Date: 2026-02-06 15:01:58.315205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a4ce4feb92b'
down_revision: Union[str, Sequence[str], None] = 'fb20cc474ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
