"""add_aluno_id_to_usuarios

Revision ID: fb20cc474ff8
Revises: 
Create Date: 2026-02-06 00:17:08.829744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb20cc474ff8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alunos', sa.Column('graduacao_id', sa.UUID(), nullable=True))
    op.alter_column('alunos', 'telefone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.create_foreign_key(None, 'alunos', 'graduacoes', ['graduacao_id'], ['id'])
    op.add_column('usuarios', sa.Column('aluno_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'usuarios', 'alunos', ['aluno_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'aluno_id')
    op.drop_constraint(None, 'alunos', type_='foreignkey')
    op.alter_column('alunos', 'telefone',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('alunos', 'graduacao_id')
    # ### end Alembic commands ###
